### ISSUE TITLE
Instructions are not clear

### ISSUE THREAD

**Issue by IdanBanani** [pwndbg/pwndbg-themes#2]
where are the themes and how do I switch between theme?

**Comment by disconnect3d** [comment]
Hey, currently, there is only @anthraxx's style he contributed to this repo.

In order to use it, you need to clone this repo (or, download his theme file: https://raw.githubusercontent.com/pwndbg/pwndbg-themes/master/anthraxx/anthraxx.pwndbg) and then use the GDB's `source` command, the same way Pwndbg itself is loaded, but targeting the `anthraxx.pwndbg` file.

A solution that just works, if you want to test out the theme is to do:
```
wget https://raw.githubusercontent.com/pwndbg/pwndbg-themes/master/anthraxx/anthraxx.pwndbg
echo "source $(pwd)/anthraxx.pwndbg" >> ~/.gdbinit
```

Hope this helps!

@IdanBanani since the README was not so clear in those, can you send a PR modifying it to make it more clear? :)

**Comment by IdanBanani** [comment]
Thank you.

Is there any chance that anthraxx theme is also the default theme? (I don't see any change in the colors after running these commands)
![111](https://user-images.githubusercontent.com/26879273/133492003-a06b72f8-eb17-409f-9c3b-3d30ec8f1e31.png)

If one wish to make the change permanent - does he need to edit his .bashrc?

**Comment by disconnect3d** [comment]
> Is there any chance that anthraxx theme is also the default theme? (I don't see any change in the colors after running these commands)

Not in a standard installation, but it may be included in the Pwndbg Arch package as @anthraxx maintains it (and maybe u use Arch Linux? :P).

> If one wish to make the change permanent - does he need to edit his .bashrc?


Pwndbg is a GDB module, so its usually loaded from ~/.gdbinit via a `source <path to pwndbg's init python file>` GDB command. The theme is loaded via a `source <theme file>` command and if you want to make it persistent such command needs to be added to your ~/.gdbinit (or other gdbinit file your GDB loads during startup).
